// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.osc.proto;

public final class User {
  private User() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_userDetailsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_userDetailsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_userDetailsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_userDetailsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\"~\n\022userDetailsRequest\022\016\n\006us" +
      "erId\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\022" +
      "\017\n\007contact\030\004 \001(\t\022\013\n\003DOB\030\005 \001(\t\022\020\n\010passwor" +
      "d\030\006 \001(\t\022\013\n\003OTP\030\007 \001(\t\"&\n\023userDetailsRespo" +
      "nse\022\017\n\007message\030\001 \001(\t2R\n\020storeUserDetails" +
      "\022>\n\017getTemplateInfo\022\023.userDetailsRequest" +
      "\032\024.userDetailsResponse\"\000B\021\n\rcom.osc.prot" +
      "oP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_userDetailsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_userDetailsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_userDetailsRequest_descriptor,
        new java.lang.String[] { "UserId", "Name", "Email", "Contact", "DOB", "Password", "OTP", });
    internal_static_userDetailsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_userDetailsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_userDetailsResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
