// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.osc.proto;

public interface userDetailsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:userDetailsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
